global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'feedback-analysis-app'
    static_configs:
      - targets: ['host.docker.internal:3000']  # Your React app
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Add your application metrics endpoint here
  # - job_name: 'your-backend-api'
  #   static_configs:
  #     - targets: ['your-api:8080']
